from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.role_home, name='home'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('staff-dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('customer-home/', views.customer_home, name='customer_home'),
    path('dashboard/', views.staff_dashboard, name='dashboard'),
    path('medicines/', views.medicines_view, name='medicines'),
    path('generics/', views.generics_view, name='generics'),
    path('suppliers/', views.suppliers_view, name='suppliers'),
    path('inventory/', views.inventory_view, name='inventory'),
    path('sales/', views.sales_view, name='sales'),
    path('sales/history/', views.sales_list_view, name='sales_list'),
    path('reports/', views.reports_view, name='reports'),
    path('ocr/', views.ocr_view, name='ocr'),
    path('recommend/', views.recommend_view, name='recommend'),
    path('online-purchase/', views.online_purchase_view, name='online_purchase'),
    path('online/medicines/', views.online_medicines_view, name='online_medicines'),
    path('online/cart/', views.online_cart_view, name='online_cart'),
    path('online/cart/add/<int:medicine_id>/', views.online_add_to_cart, name='online_add_to_cart'),
    path('online/cart/update/<int:item_id>/', views.online_update_cart_item, name='online_update_cart_item'),
    path('online/cart/remove/<int:item_id>/', views.online_remove_cart_item, name='online_remove_cart_item'),
    path('online/checkout/', views.online_checkout_view, name='online_checkout'),
    path('online/prescription/upload/', views.online_upload_prescription, name='online_upload_prescription'),
    path('online/orders/', views.online_orders_view, name='online_orders'),
    path('online/orders/<int:order_id>/', views.online_order_detail_view, name='online_order_detail'),
    path('online/orders/<int:order_id>/status/', views.online_update_order_status, name='online_update_order_status'),
    path('online/orders/<int:order_id>/invoice/', views.online_invoice_view, name='online_invoice'),
    path('online/prescriptions/<int:prescription_id>/review/', views.online_review_prescription, name='online_review_prescription'),
    path('excel-tools/', views.excel_tools_view, name='excel_tools'),
    path('excel-tools/export/', views.export_medicines_excel, name='export_medicines_excel'),
    path('excel-tools/import/', views.import_medicines_excel, name='import_medicines_excel'),
]
