# Generated by Django 4.2.7 on 2026-03-28 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy_app', '0002_customerprofile_onlinecart_onlineorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_online_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='gateway',
            field=models.CharField(blank=True, help_text='e.g. razorpay, stripe, cod', max_length=40),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('processed', 'Processed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OnlineOrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('packed', 'Packed'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='pharmacy_app.onlineorder')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
